const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

const money = (n, currency = 'UGX') => `${currency} ${Number(n || 0).toLocaleString()}`;

/**
 * Generates a monthly farm report PDF and saves it to disk.
 * @param {Object} opts
 * @param {Object} opts.farm - farm document
 * @param {Number} opts.month
 * @param {Number} opts.year
 * @param {Object} opts.data - aggregated report data (see reportController)
 * @returns {String} absolute file path of the generated PDF
 */
const generateMonthlyReportPDF = ({ farm, month, year, data }) => {
  const outDir = path.join(__dirname, '..', 'uploads', 'reports');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  const fileName = `${farm._id}-${year}-${String(month).padStart(2, '0')}.pdf`;
  const filePath = path.join(outDir, fileName);

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  const currency = farm.config?.currency || 'UGX';

  // Header
  doc
    .fillColor('#1F3D2B')
    .fontSize(22)
    .text('Fundo Farm Report', { continued: false });
  doc
    .fillColor('#2A2622')
    .fontSize(14)
    .text(`${farm.name} — ${MONTH_NAMES[month - 1]} ${year}`);
  doc.moveDown(1);
  doc.strokeColor('#C98A2C').lineWidth(2).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(1);

  const section = (title) => {
    doc.moveDown(0.6);
    doc.fillColor('#1F3D2B').fontSize(15).text(title);
    doc.fillColor('#7A4A2B').fontSize(10).text('_'.repeat(90));
    doc.fillColor('#2A2622').fontSize(11);
    doc.moveDown(0.3);
  };

  const row = (label, value) => {
    doc.fontSize(11).fillColor('#2A2622').text(`${label}: `, { continued: true }).fillColor('#000').text(`${value}`);
  };

  // Summary
  section('Summary');
  row('New livestock registered', data.summary.newLivestock);
  row('New pets registered', data.summary.newPets);
  row('Coffee harvested (kg)', data.summary.coffeeHarvestKg);
  row('Plantation harvested (units)', data.summary.plantationHarvestQty);
  row('Total sales revenue', money(data.summary.totalSalesRevenue, currency));
  row('Total expenses', money(data.summary.totalExpenses, currency));
  row('Net (revenue - expenses)', money(data.summary.netRevenue, currency));

  // Health
  section('Health & Medical Records');
  row('Livestock/Pet medical events', data.health.medicalCount);
  row('Coffee/Plantation health events', data.health.cropHealthCount);
  row('Total medical & crop-health cost', money(data.health.totalCost, currency));
  if (data.health.items.length) {
    doc.moveDown(0.2);
    data.health.items.slice(0, 20).forEach((item) => {
      doc.fontSize(10).fillColor('#444').text(
        `• ${new Date(item.date).toLocaleDateString()} — ${item.subjectName || 'Subject'}: ${item.issue} (${money(item.cost, currency)})`
      );
    });
  }

  // Produce & Harvests
  section('Produce & Harvests');
  row('Livestock produce records', data.produce.recordCount);
  row('Total produce quantity', data.produce.totalQuantity);
  row('Coffee harvest total (kg)', data.harvests.coffeeKg);
  row('Plantation harvest total', data.harvests.plantationQty);

  // New livestock/pets
  section('New Livestock & Pets Registered');
  if (data.newAnimals.length === 0) {
    doc.fontSize(10).fillColor('#666').text('No new livestock or pets registered this month.');
  } else {
    data.newAnimals.slice(0, 30).forEach((a) => {
      doc.fontSize(10).fillColor('#444').text(`• ${a.name} (${a.species}, ${a.gender}) — ${a.type}`);
    });
  }

  // Sales
  section('Sales');
  row('Number of sales', data.sales.count);
  row('Total revenue', money(data.sales.total, currency));

  // Expenses
  section('Expenses');
  row('Number of expense entries', data.expenses.count);
  row('Total expenses', money(data.expenses.total, currency));

  doc.moveDown(1.5);
  doc.fontSize(9).fillColor('#999').text(
    `Generated by Fundo on ${new Date().toLocaleString()}`,
    { align: 'right' }
  );

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
};

module.exports = { generateMonthlyReportPDF };
